from dataclasses import dataclass


FINDING_CATEGORY_DOMAIN = "DOMAIN"
FINDING_CATEGORY_URL = "URL"
FINDING_CATEGORY_ATTACHMENT = "ATTACHMENT"
FINDING_CATEGORY_AUTHENTICATION = "AUTHENTICATION"
FINDING_CATEGORY_SOCIAL_ENGINEERING = "SOCIAL_ENGINEERING"
FINDING_CATEGORY_RISK = "RISK"
FINDING_CATEGORY_UNKNOWN = "UNKNOWN"

FINDING_SEVERITY_LOW = "LOW"
FINDING_SEVERITY_MEDIUM = "MEDIUM"
FINDING_SEVERITY_HIGH = "HIGH"
FINDING_SEVERITY_CRITICAL = "CRITICAL"
FINDING_SEVERITY_UNKNOWN = "UNKNOWN"


@dataclass(frozen=True)
class Finding:
    code: str
    category: str
    severity: str
