DEFAULT_SUSPICIOUS_TLDS: set[str] = {"mov", "top", "xyz", "zip"}

DEFAULT_ALLOWED_URL_SCHEMES: set[str] = {"http", "https"}

DEFAULT_KNOWN_SHORTENERS: set[str] = {"bit.ly", "t.co", "tinyurl.com"}

DEFAULT_URGENCY_TERMS: set[str] = {"act now", "immediately", "urgent"}

DEFAULT_FINANCIAL_PRESSURE_TERMS: set[str] = {
    "account locked",
    "invoice overdue",
    "payment required",
}

DEFAULT_CREDENTIAL_REQUEST_TERMS: set[str] = {
    "confirm your login",
    "confirm your password",
    "enter your password",
    "verify your account",
}

DEFAULT_FINDING_WEIGHTS: dict[str, int] = {
    "DOMAIN_CONTAINS_PUNYCODE": 30,
    "DOMAIN_HAS_MIXED_SCRIPTS": 30,
    "DOMAIN_HAS_CONFUSABLE_CHARACTERS": 30,
    "DOMAIN_HAS_SUSPICIOUS_DEPTH": 15,
    "DOMAIN_LOOKS_LIKE_IP_ADDRESS": 15,
    "DOMAIN_HAS_SUSPICIOUS_TLD": 20,
    "URL_SCHEME_NOT_ALLOWED": 15,
    "URL_HAS_SUSPICIOUS_SCHEME": 30,
    "URL_HAS_EMBEDDED_CREDENTIALS": 25,
    "URL_HAS_SUSPICIOUS_QUERY_DENSITY": 15,
    "URL_USES_KNOWN_SHORTENER_DOMAIN": 15,
    "ATTACHMENT_HAS_EXECUTABLE_EXTENSION": 40,
    "ATTACHMENT_HAS_OFFICE_DOCUMENT_EXTENSION": 15,
    "ATTACHMENT_HAS_DOUBLE_EXTENSION": 30,
    "ATTACHMENT_HAS_SUSPICIOUS_FILENAME_CHARS": 30,
    "AUTHENTICATION_SPF_FAILED": 25,
    "AUTHENTICATION_DKIM_FAILED": 25,
    "AUTHENTICATION_DMARC_FAILED": 50,
    "AUTHENTICATION_HAS_MULTIPLE_FAILURES": 50,
    "AUTHENTICATION_RESULTS_UNKNOWN": 15,
    "SOCIAL_ENGINEERING_HAS_URGENCY_TERMS": 10,
    "SOCIAL_ENGINEERING_HAS_FINANCIAL_PRESSURE_TERMS": 15,
    "SOCIAL_ENGINEERING_HAS_CREDENTIAL_REQUEST_TERMS": 25,
}

DEFAULT_CRITICAL_INDICATORS: set[str] = {
    "ATTACHMENT_HAS_EXECUTABLE_EXTENSION",
    "AUTHENTICATION_DMARC_FAILED",
    "AUTHENTICATION_HAS_MULTIPLE_FAILURES",
}
