from __future__ import annotations

import re
import sys
from pathlib import Path


ALLOWED_SUMMARY_PATTERN = re.compile(
    r"^(feat|fix|docs|test|refactor|chore|release|ci)\([a-z0-9-]+\): [A-Z].+\.$",
)
ALLOWED_AUTOGENERATED_PREFIXES = (
    "Merge pull request #",
    "Merge branch ",
    "Auto PR:",
)
BODY_BULLET_PATTERN = re.compile(r"^- [A-Z].*\.$")


def _filtered_lines(message_text: str) -> list[str]:
    return [line.rstrip() for line in message_text.splitlines() if not line.startswith("#")]


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: python scripts/check_commit_message.py <commit-message-file>")
        return 1

    message_path = Path(sys.argv[1])
    lines = _filtered_lines(message_path.read_text(encoding="utf-8"))

    if not lines:
        print("Commit message is empty.")
        return 1

    summary = lines[0].strip()
    if summary.startswith(ALLOWED_AUTOGENERATED_PREFIXES):
        return 0

    if not ALLOWED_SUMMARY_PATTERN.match(summary):
        print("Commit summary must match 'type(scope): Action summary.' with an uppercase initial and final period.")
        return 1

    if len(lines) == 1:
        print("Non-trivial commits must include a blank line and at least one body bullet.")
        return 1

    if lines[1] != "":
        print("Commit message must include a blank line between the summary and body.")
        return 1

    body_lines = [line for line in lines[2:] if line.strip()]
    if not body_lines:
        print("Commit message body must include at least one bullet line.")
        return 1

    invalid_body_lines = [line for line in body_lines if not BODY_BULLET_PATTERN.match(line)]
    if invalid_body_lines:
        print("Commit body lines must use '- Body bullet.' format with an uppercase initial and final period.")
        for line in invalid_body_lines:
            print(f"- Invalid line: {line}")
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
